services:
  - type: web
    name: barrel-brawl
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
