services:
  - type: web
    name: barrel-brawl
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
